version: '3.9'
services:
  dd-agent:
    image: datadog/agent:latest
    ports:
      - "127.0.0.1:8126:8126"
      - "127.0.0.1:5555:5555"
    networks:
      - privateNetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    env_file:
      - ./../.env
    environment:
      DD_LOGS_ENABLED: true
      DD_DOCKER_LABELS_AS_TAGS: true
      DD_PROCESS_AGENT_ENABLED: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
      DD_PROCESS_AGENT_CONTAINER_SOURCE: "docker"
      DD_LOG_LEVEL: warn
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
      DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE: true
      DD_CONTAINER_EXCLUDE_LOGS: "name:dd-agent"
      DD_APM_ENABLED: true
      DD_HEALTH_PORT: true
      DD_BIND_HOST: "0.0.0.0"
      DD_SITE: "datadoghq.com"
  api:
    build: 
      context: ../.
      dockerfile: dockerfile
    labels:
      com.datadoghq.ad.logs: '[{"source": "node", "service": "webapp"}]'
    command: 'start'
    environment:
      ENABLE_DATADOG: true
      DD_ENV: "prod"
      DD_PROFILING_ENABLED: true
      DD_TRACE_ENABLED: true
      DD_RUNTIME_METRICS_ENABLED: true
      DD_LOGS_INJECTION: true
      DD_HOSTNAME: 'dd-agent'
      DD_APM_ENABLED: true
      DD_LOG_LEVEL: 'trace'
      DD_DOGSTATSD_URL: udp://dd-agent:8125
      DD_TRACE_AGENT_URL: http://dd-agent:8126
    networks:
      - privateNetwork
    depends_on:
      - dd-agent
  loadtester:
    build: 
      context: ../.
      dockerfile: dockerfile
    labels:
      com.datadoghq.ad.logs: '[{"source": "node", "service": "loadtester"}]'
    command: 'test'
    depends_on:
      - api
    environment: 
      BASE_URL: 'http://api:8080'
      REQUEST_LOAD: 1000
      WORKER_COUNT: 10
      STARTING_SLEEP: 100
    networks:
      - privateNetwork

networks:
  privateNetwork:
    name: node-dd-demo
    external: true

