version: '3.9'
services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      DD_APM_ENABLED: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_LOGS_ENABLED: true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
      DD_CONTAINER_EXCLUDE: 'name:datadog-agent'
  api:
    build: 
      context: ../.
      dockerfile: dockerfile
    labels:
      com.datadoghq.ad.logs: '[{"source": "node", "service": "webapp"}]'
    command: 'start'
    environment:
      DD_HOSTNAME: 'datadog-agent'
      DD_APM_ENABLED: true
      ENABLE_DATADOG: true
      DD_LOG_LEVEL: 'trace'
    networks:
      - privateNetwork
    depends_on:
      - datadog-agent
  loadtester:
    build: 
      context: ../.
      dockerfile: dockerfile
    labels:
      com.datadoghq.ad.logs: '[{"source": "node", "service": "loadtester"}]'
    command: 'test'
    depends_on:
      - api
    environment: 
      BASE_URL: 'http://api:8080'
      REQUEST_LOAD: 10000
      WORKER_COUNT: 100
      STARTING_SLEEP: 100
    networks:
      - privateNetwork

networks:
    privateNetwork:
        name: private-networks
